# Generated by Django 2.2.16 on 2022-08-25 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='ConfirmationCode',
        ),
    ]
