# Generated by Django 2.2.16 on 2022-08-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220825_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_moderator',
            field=models.BooleanField(blank=True, default=False, verbose_name='Moderator status'),
        ),
    ]
