# Generated by Django 2.2.16 on 2022-08-28 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220828_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Title', 'verbose_name_plural': 'Titles'},
        ),
    ]
