# Generated by Django 2.2.16 on 2022-08-27 14:48

from django.db import migrations
import reviews.managers


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_user_is_moderator'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', reviews.managers.CustomUserManager()),
            ],
        ),
    ]
