# Generated by Django 3.2.15 on 2022-08-23 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_rename_title_review_title_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='review',
            new_name='review_id',
        ),
    ]
