# Generated by Django 3.2.15 on 2022-08-23 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_rename_review_comment_review_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titlegenre',
            old_name='genre',
            new_name='genre_id',
        ),
        migrations.RenameField(
            model_name='titlegenre',
            old_name='title',
            new_name='title_id',
        ),
    ]
