# Generated by Django 3.2 on 2022-08-24 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20220824_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titlegenre',
            options={'ordering': ('title_id',)},
        ),
        migrations.AlterField(
            model_name='titlegenre',
            name='genre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.genre', verbose_name='Название жанра'),
        ),
        migrations.AlterField(
            model_name='titlegenre',
            name='title_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.title', verbose_name='Название произведения'),
        ),
        migrations.AddConstraint(
            model_name='titlegenre',
            constraint=models.UniqueConstraint(fields=('title_id', 'genre_id'), name='unique genre'),
        ),
    ]
